from abc import ABC, abstractmethod
from app.domain.models.tool_approval_rule import ToolApprovalRule

class ToolApprovalRuleRepository(ABC):
    @abstractmethod
    async def find_by_user_and_tool(self, user_id: str, tool_name: str) -> list[ToolApprovalRule]: ...
    @abstractmethod
    async def create(self, rule: ToolApprovalRule) -> ToolApprovalRule: ...
    @abstractmethod
    async def delete(self, rule_id: str) -> None: ...
    @abstractmethod
    async def find_by_user(self, user_id: str) -> list[ToolApprovalRule]: ...
